version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Assurez-vous que le fichier de configuration Nginx est présent
      - ./nginx_logs:/var/log/nginx  # Dossier où les logs Nginx sont stockés
    ports:
      - "80:80"
    networks:
      - loki-network

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./nginx_logs:/var/log/nginx
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - loki-network
    depends_on:
      - loki
      - promtail

networks:
  loki-network:
    driver: bridge

